### ISSUE TITLE
Sample files are interpreted as new TV shows

### ISSUE THREAD

**Issue by hurtauda** [jonag/Episodes#1]
When running the script against a folder where there is an episode and a sample.
The episode is correctly processed but the sample video file also and create a new "TV show" folder with the sample name.

Files with problems :
   Angie.Tribeca.S01E07.720p.HDTV.x264-KILLERS.mkv  689.97 MB
   RARBG.com.txt    0.03 KB
   Sample/sample-angie.tribeca.s01e07.720p.hdtv.x264-killers.mkv    49.86 MB
   angie.tribeca.s01e07.720p.hdtv.x264-killers.nfo  10.62 KB

Anyway, awesome job :+1: 
hurtauda

**Comment by jonag** [comment]
I can either set a minimum size for an episode or ignore all files with "sample" in their name.

I will choose option 2 for now since it's hard to define a minimum size, and according to thetvdb there is only one show with "sample" in its name.

If someone has a better solution, I'm interested.
